version: "3.1"

services:
    db:
        container_name: db-fabrica
        image: postgres
        restart: always
        environment:
            POSTGRES_PASSWORD: docker
        ports:
            - 5432:5432
